export const REMOVE_FAVORITE_RECIPE_REQUEST = "REMOVE_FAVORITE_RECIPE_REQUEST";
export const REMOVE_FAVORITE_RECIPE_SUCCESS = "REMOVE_FAVORITE_RECIPE_SUCCESS";
export const REMOVE_FAVORITE_RECIPE_FAIL = "REMOVED_FAVORITE_RECIPE_FAIL";
export const REMOVE_FAVORITE_RECIPE_RESET = "REMOVE_FAVORITE_RECIPE_RESET";
