export const RECIPE_CREATE_REVIEW_REQUEST = "RECIPE_CREATE_REVIEW_REQUEST";
export const RECIPE_CREATE_REVIEW_SUCCESS = "RECIPE_CREATE_REVIEW_SUCCESS";
export const RECIPE_CREATE_REVIEW_FAIL = "RECIPE_CREATE_REVIEW_FAIL";
export const RECIPE_CREATE_REVIEW_RESET = "RECIPE_CREATE_REVIEW_RESET";
